import manifestJson from "../../../content/pl-400/manifest.json";
import lessonSectionsJson from "../../../content/pl-400/lesson-sections.json";
import type { ContentManifest, RubricScores } from "@learn/mastery-gate/schema";

export const manifest = manifestJson as unknown as ContentManifest;

/**
 * Lesson sections rendered on /pl-400 and used as remediation-anchor targets.
 * Generated by scripts/port-lessons.ts from the authored lesson specs —
 * regenerate rather than hand-editing so the markdown lessons, the manifest
 * anchors, and this list cannot drift apart.
 */
export const lessonSections: { id: string; title: string; body: string[] }[] =
  lessonSectionsJson as { id: string; title: string; body: string[] }[];

/**
 * Verbatim lesson-body sentence the agent-less "score rubric at mastery"
 * demo button submits as evidence. Must remain an exact substring of a
 * lessonSections body line or the facade's verbatim-corpus check rejects
 * the demo submission (guarded by content.test.ts).
 */
export const DEMO_MASTERY_QUOTE =
  "A policy is not a vote; it is a boundary.";

export const DEFAULT_SCORES: RubricScores = {
  recall: 0,
  connections: 0,
  application: 0,
  transfer: 0,
};
