import manifestJson from "../../../content/pl-400/manifest.json";
import lessonSectionsJson from "../../../content/pl-400/lesson-sections.json";
import type { ContentManifest, RubricScores } from "@learn/mastery-gate/schema";

export const manifest = manifestJson as unknown as ContentManifest;

/**
 * Lesson section text generated by scripts/port-lessons.ts from the authored
 * lesson specs. Since the micro-lesson restore, these sections are NOT
 * rendered on the /pl-400 hub — remediation anchors live on the per-lesson
 * pages (/pl-400/[slug]) and navigate_to_anchor from the hub is a cross-page
 * navigation handled by AnchorNavigator. This list remains the rubric
 * evidence corpus (facade evidenceCorpus) and must stay in sync with the
 * lesson pages — regenerate rather than hand-editing.
 */
export const lessonSections: { id: string; title: string; body: string[] }[] =
  lessonSectionsJson as { id: string; title: string; body: string[] }[];

/**
 * Verbatim lesson-body sentence the agent-less "score rubric at mastery"
 * demo button submits as evidence. Must remain an exact substring of a
 * lessonSections body line or the facade's verbatim-corpus check rejects
 * the demo submission (guarded by content.test.ts).
 */
export const DEMO_MASTERY_QUOTE =
  "A policy is not a vote; it is a boundary.";

export const DEFAULT_SCORES: RubricScores = {
  recall: 0,
  connections: 0,
  application: 0,
  transfer: 0,
};
