import lessonIndexJson from "../../../content/pl-400/lesson-index.json";

/**
 * Slim per-lesson index generated by scripts/port-lessons.ts. This is the
 * ONLY lesson module client bundles may import for routing/scoping/progress:
 * it carries no scenario, distractor, drill, or reference prose, so the full
 * teaching catalog (lesson-pages.json) stays out of the shared JS chunks
 * (cross-review finding 8). The full catalog loader (lessonPages.ts) is
 * reserved for server components.
 */
export interface LessonIndexEntry {
  id: string;
  slug: string;
  title: string;
  topicTitle: string;
  heroEpigraph: string;
  objectiveId: string;
  questionIds: string[];
}

export const lessonIndex: LessonIndexEntry[] =
  lessonIndexJson as LessonIndexEntry[];

export function getLessonIndexEntry(
  slug: string,
): LessonIndexEntry | undefined {
  return lessonIndex.find((entry) => entry.slug === slug);
}

/**
 * The six remediation-anchor targets every lesson page renders, each paired
 * with the title of the section it names — so get_current_context and
 * get_lesson_brief can tell the agent where it is sending the learner.
 * Titles must stay verbatim-truthful to the headings LessonPage renders.
 */
export function lessonSectionAnchorEntries(
  slug: string,
): { anchor: string; title: string }[] {
  return [
    { anchor: `${slug}-rule`, title: "Governing rule" },
    { anchor: `${slug}-exam-clue`, title: "Exam-recognition clue" },
    {
      anchor: `${slug}-scenario`,
      title: "01 / Scenario — make the decision before seeing the mechanism",
    },
    { anchor: `${slug}-production`, title: "Production nuance" },
    {
      anchor: `${slug}-compress`,
      title: "02 / Compress the rule — state the load-bearing rule in one line",
    },
    { anchor: `${slug}-run`, title: "08 / Run — decide what this changes" },
  ];
}

export function lessonSectionAnchors(slug: string): string[] {
  return lessonSectionAnchorEntries(slug).map((entry) => entry.anchor);
}

export interface SectionMapEntry {
  anchor: string;
  /** Full section title (verbatim from lessonSectionAnchorEntries). */
  title: string;
  /** Compact rail label: the part before " — " when present, else the full title. */
  shortLabel: string;
}

export function sectionMapEntries(slug: string): SectionMapEntry[] {
  return lessonSectionAnchorEntries(slug).map((entry) => {
    const cut = entry.title.indexOf(" — ");
    return {
      anchor: entry.anchor,
      title: entry.title,
      shortLabel: cut === -1 ? entry.title : entry.title.slice(0, cut),
    };
  });
}

const ANCHOR_OWNER_BY_ID = new Map<string, string>();
const LESSON_BY_QUESTION_ID = new Map<string, LessonIndexEntry>();
for (const entry of lessonIndex) {
  for (const anchor of lessonSectionAnchors(entry.slug)) {
    ANCHOR_OWNER_BY_ID.set(anchor, entry.slug);
  }
  for (const questionId of entry.questionIds) {
    LESSON_BY_QUESTION_ID.set(questionId, entry);
  }
}

export function anchorOwnerSlug(anchor: string): string | null {
  return ANCHOR_OWNER_BY_ID.get(anchor) ?? null;
}

export function lessonForQuestion(
  questionId: string,
): LessonIndexEntry | null {
  return LESSON_BY_QUESTION_ID.get(questionId) ?? null;
}

/**
 * The governing-rule anchor of the lesson that owns a question — the
 * same-lesson fallback for review/coach routing when no misconception-
 * specific anchor is available (cross-review finding 3).
 */
export function ruleAnchorForQuestion(questionId: string): string | null {
  const entry = lessonForQuestion(questionId);
  return entry ? `${entry.slug}-rule` : null;
}
